### ISSUE TITLE
SGE and DRK bugs

### ISSUE THREAD

**Issue by RiotNOR** [ArchiDog1998/FFXIVRotations#31]
Sage will spam Physios 2 and Phlegma when trying to heal. Was testing the new rotation fixes by Nore and was at a Lvl 60 24man raid. This is noticable when your character is low health and it's trying to AOE heal. It will spam these despite being on cooldown.

Dark Knight will instantly cast Delirium and Blood Weapon when Rotation Solver is turned on. This is expected behavior for CountDownAction(), but not out in the open. Users should not conform to new patterns of use for specific rotations. Cannot reproduce by going in solo to same instance (Cloud Deck), so unsure what is causing it. Most likely a check with RatioOfMembersIn2MinBurst.

**Comment by ArchiDog1998** [comment]
@ThesisNegatif Uhhh...
