### ISSUE TITLE
MCH not always using Hypercharge during Wildfire

### ISSUE THREAD

**Issue by KalasB** [ArchiDog1998/FFXIVRotations#43]
During the fight, the general purpose MCH rotation seems to wait for 50 heat gauge before executing Wildfire, but then doesn't always go into Hypercharge.

**Comment by ArchiDog1998** [comment]
Thanks for your feedback. I am not good at any job, so it'll take me a lot of time to learn that job. I raise a vote about which rotation shall I rewrite in discord. You can vote on this job [here](https://discord.com/channels/1064448004498653245/1064747723376566334/1104584104772640788).
