### ISSUE TITLE
Invalid rotation... again

### ISSUE THREAD

**Issue by Kumicoo** [ArchiDog1998/FFXIVRotations#47]
Hey. Got "Invalid rotation" for MCH and some other classes again. Why is that? I waited 2 days, but its still not fixed. i am on 2.8.0.

**Comment by Niahmi** [comment]
> Hey. Got "Invalid rotation" for MCH and some other classes again. Why is that? I waited 2 days, but its still not fixed. i am on 2.8.0.

--

2.8.0 is currently bugged and the author is away on a trip. You can fix the issue locally for now by reverting to a previous version of the plugin from the releases page. In case you're unsure how to do this, I'll give you a brief outline:

-> disable the rotations, and auto-update rotations within the plugin while in-game, then quit the game

-> download the releases and rotations files from [here](https://github.com/ArchiDog1998/RotationSolver/releases/tag/v2.7.7) and [here](https://github.com/ArchiDog1998/FFXIVRotations/releases/tag/v1.0.15).

-> Go to C:/Users/[Your Username Here]/AppData/Roaming/XIVLauncher/installedPlugins/RotationSolver and copy/paste in the RotationSolver files from the first link.

-> Now go to C:/Users/[Your Username Here]/AppData/Roaming/XIVLauncher/pluginConfigs/RotationSolver/Rotations and copy/paste in the rotations files from the second link.

You can now load up the game and carry on playing with RotationSolver until a fix comes out. If you run into issues while trying to do this, I suggest you join the project discord server [here](https://discord.gg/4fECHunam9) and you can receive help there; or if you would just like to stay up to date with the project. 

I hope that this helps, and I hope you have a good day :)
