### ISSUE TITLE
NIN not doing Chi

### ISSUE THREAD

**Issue by thisischrys** [ArchiDog1998/FFXIVRotations#93]
NIN always stops when it is time to use Chi (it is highlighted) the first time in the rotation. So i have to press it myself.
Then the second time it stops on Chi AND on Jin.

**Comment by ArchiDog1998** [comment]
It works fine on my machine! I just tested it!
NIN is the issue rotation. For some reason, it is not stable on some servers, excluding where I am.
So... My suggestion is switching to another job!

**Comment by thisischrys** [comment]
Understandable, it does the same even with XIVSlothCombo.
And yeah it does every other job without problems so far.
Thanks for the excellent plugin!

**Comment by Rabalaba** [comment]
can you try changing 
        public static IBaseAction Ten { get; } = new BaseAction(ActionID.Ten, ActionOption.Friendly);
        public static IBaseAction Chi { get; } = new BaseAction(ActionID.Chi, ActionOption.Friendly);
        public static IBaseAction Jin { get; } = new BaseAction(ActionID.Jin, ActionOption.Friendly);
to
        public static IBaseAction Ten { get; } = new BaseAction(ActionID.Ten);
        public static IBaseAction Chi { get; } = new BaseAction(ActionID.Chi);
        public static IBaseAction Jin { get; } = new BaseAction(ActionID.Jin);

Its hard to reproduce this bug but after exhaustive testing this seemed to work

**Comment by thisischrys** [comment]
I got a mail saying my issue had an update with a solution, but I don't see it in here so reopening:

Rabalaba <notifications@github.com> Unsubscribe
3:19 PM (2 hours ago)
to ArchiDog1998/FFXIVRotations, me, State

can you try changing
public static IBaseAction Ten { get; } = new BaseAction(ActionID.Ten, ActionOption.Friendly);
public static IBaseAction Chi { get; } = new BaseAction(ActionID.Chi, ActionOption.Friendly);
public static IBaseAction Jin { get; } = new BaseAction(ActionID.Jin, ActionOption.Friendly);
to
public static IBaseAction Ten { get; } = new BaseAction(ActionID.Ten);
public static IBaseAction Chi { get; } = new BaseAction(ActionID.Chi);
public static IBaseAction Jin { get; } = new BaseAction(ActionID.Jin);

Its hard to reproduce this bug but after exhaustive testing this seemed to work

**Comment by Rabalaba** [comment]
Bug returned so I deleted post
